---

- name: install and configure IBM InfoSphere Information Server
  hosts: all
  any_errors_fatal: true
  roles:
    - IBM.infosvr

  pre_tasks:
    - name: check /proc/version
      command: cat /proc/version
      register: __ibm_infosvr_proc_version
    - name: bind /proc/version
      command: mount --bind /root/proc_version /proc/version
      args:
        warn: False
      when: __ibm_infosvr_proc_version.stdout.find('Red Hat') == -1

  post_tasks:
    - name: shutdown Information Server
      import_role:
        name: IBM.infosvr
        tasks_from: stop.yml
    - name: cleanup any unused files
      shell: rm -rf {{ item }}
      args:
        executable: /bin/bash
        warn: False
      with_items:
        - "{{ ibm_infosvr_install_location.linux }}/isdump-redhat-*"
        - "{{ ibm_infosvr_install_location.linux }}/Updates/Downloads"
        - "{{ ibm_infosvr_install_location.linux }}/Updates/Backup.*"
        - "{{ ibm_infosvr_install_location.linux }}/Updates/_jvm.*"
        - "{{ ibm_infosvr_install_location.linux }}/Updates/server.*"
        - "/tmp/*"
