---
###
# Copyright 2018 IBM Corp. All Rights Reserved.
# 
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
# 
#      http://www.apache.org/licenses/LICENSE-2.0
# 
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
###

- import_role: name=cmgrote.ibm-infosvr-metadata-asset-manager
  no_log: True
  vars:
    ibm_infosvr_metadata_asset_mgr_import_areas:
      - 
        name: IADB
        type: DB2Connector
        description: "Automated ingestion of database tables used by Information Analyzer"
        metadata_interchange_server: "{{ hostvars[inventory_hostname].ansible_fqdn|lower }}"
        dcn:
          name: IADB
          description: "DCN for the schema containing Information Analyzer analysis database"
          database: IADB
          username: "{{ ibm_infosvr_user_ia }}"
          password: "{{ ibm_infosvr_upwd_ia }}"
        hostname: "{{ hostvars[ibm_infosvr_hosts.engine].ansible_fqdn | upper }}"
        database_name: IADB
  become_user: "{{ ibm_infosvr_user_dsadmin }}"
  become: yes
  when: ('ibm-information-server-engine' in group_names)

- name: configure-ia - set default credential mapping
  shell: >
          {{ ibm_infosvr_install_location.linux }}/ASBNode/bin/DirectoryCommand.sh
          -user {{ ibm_infosvr_user_isadmin }}
          -password {{ ibm_infosvr_upwd_isadmin }}
          -url https://{{ ibm_infosvr_hosts.domain }}:{{ ibm_infosvr_ports.console }}
          -datastage_server {{ hostvars[inventory_hostname].ansible_fqdn }}
          -set_default_ds_credentials '{{ ibm_infosvr_user_dsadmin }}~{{ ibm_infosvr_upwd_dsadmin }}'
  args:
    executable: /bin/bash
  become_user: "{{ ibm_infosvr_user_dsadmin }}"
  become: yes
  when: ('ibm-information-server-engine' in group_names)

- name: configure-ia - assign additional necessary roles to isadmin user (for UGDefaultWorkspace)
  shell: >
          {{ ibm_infosvr_install_location.linux }}/ASBNode/bin/DirectoryCommand.sh
          -user {{ ibm_infosvr_user_isadmin }}
          -password {{ ibm_infosvr_upwd_isadmin }}
          -url https://{{ ibm_infosvr_hosts.domain }}:{{ ibm_infosvr_ports.console }}
          -assign_user_roles '{{ ibm_infosvr_user_isadmin }}$SorcererAdmin~SorcererUser~SorcererDataAdmin~RulesUser~RulesAuthor~RulesAdministrator~RulesManager'
  args:
    executable: /bin/bash
  become_user: "{{ ibm_infosvr_user_dsadmin }}"
  become: yes
  when: ('ibm-information-server-engine' in group_names)

- name: configure-ia - copy DQ configuration (v11.7)
  copy: src=dqConfig.json dest=/tmp/dqConfig.json
  become_user: "{{ ibm_infosvr_user_dsadmin }}"
  become: yes
  when: ('ibm-information-server-engine' in group_names) and (__ibm_infosvr_version == "11.7")

- name: configure-ia - update DQ configuration to enable actionable rules (v11.7)
  shell: >
          {{ ibm_infosvr_install_location.linux }}/ASBNode/bin/IAAdmin.sh
          -user {{ ibm_infosvr_user_isadmin }}
          -password {{ ibm_infosvr_upwd_isadmin }}
          -url https://{{ ibm_infosvr_hosts.domain }}:{{ ibm_infosvr_ports.console }}
          {{ item }}
  args:
    executable: /bin/bash
  with_items:
    - "-setDataQualityConfig -content /tmp/dqConfig.json"
    - "-setDataQualityConfig -content /tmp/dqConfig.json -projectName UGDefaultWorkspace"
  become_user: "{{ ibm_infosvr_user_dsadmin }}"
  become: yes
  when: ('ibm-information-server-engine' in group_names) and (__ibm_infosvr_version == "11.7")

- name: configure-ia - post DQ configuration change (v11.7)
  uri:
    url: "{{ item }}"
    method: POST
    user: "{{ ibm_infosvr_user_isadmin }}"
    password: "{{ ibm_infosvr_upwd_isadmin }}"
    body: '{"useAutomaticConfiguration":true}'
    validate_certs: no
    status_code: 200
    headers:
      Content-Type: "application/json"
  with_items:
    - "https://{{ ibm_infosvr_hosts.domain }}:{{ ibm_infosvr_ports.console }}/ibm/iis/ia/api/configuration/project/UGDefaultWorkspace/dataQuality"
    - "https://{{ ibm_infosvr_hosts.domain }}:{{ ibm_infosvr_ports.console }}/ibm/iis/ia/api/configuration/dataQuality"
  become_user: "{{ ibm_infosvr_user_dsadmin }}"
  become: yes
  when: ('ibm-information-server-engine' in group_names) and (__ibm_infosvr_version == "11.7")

- name: configure-ia - copy IA engine node configuration
  template: src=ia.job.properties.j2 dest={{ ibm_infosvr_install_location.linux }}/ASBNode/conf/ia.job.properties
  become_user: root
  become: yes
  when: ('ibm-information-server-engine' in group_names)

- name: configure-ia - configure global analysis database settings
  shell: >
          {{ ibm_infosvr_install_location.linux }}/ASBServer/bin/IAAdmin.sh
          -user {{ ibm_infosvr_user_isadmin }}
          -password {{ ibm_infosvr_upwd_isadmin }}
          -url https://{{ ibm_infosvr_hosts.domain }}:{{ ibm_infosvr_ports.console }}
          -setIADBParams
          -iaDBHost {{ hostvars[ibm_infosvr_hosts.engine].ansible_fqdn | upper }}
          -iaDBDataConnection IADB
          -iaDataSource jdbc/IADB
  args:
    executable: /bin/bash
  when: ('ibm-information-server-domain' in group_names)

# MOVED to separate ibm-infosvr-ug role
#- name: configure-ia - transfer new default ODF parameters (v11.7)
#  template: src=ODFParams.json.j2 dest=/tmp/ODFParams.json
#  when: ('ibm-information-server-domain' in group_names) and (__ibm_infosvr_version == "11.7")
#
#- name: configure-ia - enable Unified Governance additions (v11.7)
#  shell: >
#          {{ ibm_infosvr_install_location.linux }}/ASBServer/bin/iisAdmin.sh
#          -set
#          {{ item }}
#  args:
#    executable: /bin/bash
#  with_items:
#    - "-key com.ibm.iis.ug11_7.autoclassification.enabled -value true"
#    - "-key com.ibm.iis.ug11_7.autoclassification.dopublish -value true"
#    - "-key com.ibm.iis.ia.server.jobs.results.bridge -value odf"
#    - "-key com.ibm.iis.odf.autoclassification.configuration -value 'CA,TM,DQ'"
#  when: ('ibm-information-server-domain' in group_names) and (__ibm_infosvr_version == "11.7")
#
#- name: configure-ia - enable Unified Governance IA additions (v11.7)
#  shell: >
#          {{ ibm_infosvr_install_location.linux }}/ASBServer/bin/IAAdmin.sh
#          -user {{ ibm_infosvr_user_isadmin }}
#          -password {{ ibm_infosvr_upwd_isadmin }}
#          -url https://{{ ibm_infosvr_hosts.domain }}:{{ ibm_infosvr_ports.console }}
#          {{ item }}
#  args:
#    executable: /bin/bash
#  with_items:
#    - "-setODFParams -content /tmp/ODFParams.json"
#    - "-setODFParams -content /tmp/ODFParams.json -projectName UGDefaultWorkspace"
#  when: ('ibm-information-server-domain' in group_names) and (__ibm_infosvr_version == "11.7")
#
#- name: configure-ia - enable ML-based term classification (Finley v11.7)
#  shell: >
#          {{ ibm_infosvr_install_location.linux }}/ASBServer/bin/iisAdmin.sh
#          -set
#          {{ item }}
#  args:
#    executable: /bin/bash
#  with_items:
#    - "-key com.ibm.iis.odf.PredictorServiceEndpoint -value '{{ hostvars[ibm_infosvr_hosts.ug].ansible_fqdn|lower }}:{{ ibm_infosvr_ports.ug_console }}'"
#    - "-key com.ibm.iis.ug11_7.odfservices.ta -value 'com.ibm.iis.odf.services.termassignment.finley.FinleyPredictorService,com.ibm.iis.odf.services.termclassification.matching.bg.MatcherDiscoveryService,com.ibm.iis.odf.iisext.services.cbta.ClassBasedTermAssignmentService'"
#  when: ('ibm-information-server-domain' in group_names) and (__ibm_infosvr_features.ml_term_assignment) and (__ibm_infosvr_version == "11.7")
