---
###
# Copyright 2018 IBM Corp. All Rights Reserved.
# 
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
# 
#      http://www.apache.org/licenses/LICENSE-2.0
# 
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
###

##########
# POST-INSTALL CONFIG
- name: configure - re-generate config for open source utilities
  shell: "{{ item }}"
  with_items:
    - "{{ ibm_infosvr_install_location.linux }}/shared-open-source/zookeeper/update-config.sh"
    - "{{ ibm_infosvr_install_location.linux }}/shared-open-source/solr/update-config.sh"
    - "{{ ibm_infosvr_install_location.linux }}/shared-open-source/kafka/update-config.sh"

# This if statement in the open source scripts doesn't really work
# -- if you're already the user the command needs to execute as it should just execute, without su
#    (trying to use su in a more secure environment where root has nologin defined won't work, for example)
- name: configure - modify open source services scripts (v11.5)
  replace:
    dest: "{{ item }}"
    regexp: '(\s+)if \[ -n (\S+) \]; then'
    replace: '\1if [ -n \2 -a \2 != `whoami` ]; then'
    backup: yes
  with_items:
    - "/etc/init.d/InfoSrvKafka"
    - "/etc/init.d/InfoSrvSolrCloud"
    - "/etc/init.d/InfoSrvZookeeper"
  when: (__ibm_infosvr_version == "11.5")

# Next two tasks for RHEL 7 only (extrapolated from other services)
- name: configure - configure open source services systemd restartability
  template:
    src: "{{ item.src }}"
    dest: /etc/systemd/system/{{ item.svc }}
    owner: root
    group: root
    mode: "0644"
  with_items:
    - { src: InfoSrvKafka.service.j2, svc: InfoSrvKafka.service }
    - { src: InfoSrvSolrCloud.service.j2, svc: InfoSrvSolrCloud.service }
    - { src: InfoSrvZookeeper.service.j2, svc: InfoSrvZookeeper.service }
  when: >
        (ansible_distribution == "RedHat" or ansible_distribution == "CentOS")
        and (ansible_distribution_major_version == "7")
        and (__ibm_infosvr_version == "11.5")

- name: configure - register services in systemd (RHEL7 + v11.5)
  systemd: name={{ item }} enabled=yes state=started daemon_reload=yes
  with_items:
    - "InfoSrvKafka.service"
    - "InfoSrvSolrCloud.service"
    - "InfoSrvZookeeper.service"
  when: >
        (ansible_distribution == "RedHat" or ansible_distribution == "CentOS")
        and (ansible_distribution_major_version == "7")
        and (__ibm_infosvr_version == "11.5")

- name: configure - configure solr for Information Analyzer (linux) (v11.5)
  shell: >
          export JAVA_HOME={{ ibm_infosvr_install_location.linux }}/jdk/jre &&
          cd {{ ibm_infosvr_install_location.linux }}/shared-open-source/solr/install/bin &&
          ./solr create_collection
          -c da-datasets
          -shards 1
          -replicationFactor 1
          -port 58983
          -d {{ ibm_infosvr_install_location.linux }}/ASBServer/solr_configs/da_datasets_configs
  args:
    creates: "{{ ibm_infosvr_install_location.linux }}/shared-open-source/solr/data/1/da-datasets_shard1_replica1/data"
  when: ('ibm-information-server-domain' in group_names) and (__ibm_infosvr_version == "11.5")

- name: configure - update Solr indices
  uri:
    url: https://{{ ibm_infosvr_hosts.domain }}:{{ ibm_infosvr_ports.console }}/ibm/iis/dq/da/rest/v1/reindex?batchSize=25&solrBatchSize=100&upgrade=true&force=true
    method: GET
    user: "{{ ibm_infosvr_user_isadmin }}"
    password: "{{ ibm_infosvr_upwd_isadmin }}"
    force_basic_auth: yes
    status_code: 200
    validate_certs: no
  ignore_errors: yes

# MOVED to separate ibm-infosvr-ug role
#- name: configure - enable Unified Governance additions (v11.7)
#  shell: >
#          {{ ibm_infosvr_install_location.linux }}/ASBServer/bin/iisAdmin.sh
#          -set
#          {{ item }}
#  args:
#    executable: /bin/bash
#  with_items:
#    - "-key com.ibm.iis.isf.security.AllowedRefererDomainNames -value '{{ hostvars[ibm_infosvr_hosts.ug].ansible_domain|lower }}'"
#    - "-key com.ibm.iis.ug.11_7_da_datasets_index_schema -value true"
#    - "-key com.ibm.iis.ug.host.name -value '{{ hostvars[ibm_infosvr_hosts.ug].ansible_fqdn|lower }}'"
#  when: (__ibm_infosvr_version == "11.7")
