---
###
# Copyright 2018 IBM Corp. All Rights Reserved.
# 
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
# 
#      http://www.apache.org/licenses/LICENSE-2.0
# 
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
###

- import_tasks: refresh_install_details.yml

##########
# UPDATE THE INSTALLER
- name: patch - create directories
  win_file: path={{ item }} state=directory
  with_items:
    - "{{ ibm_infosvr_install_location.win }}\\Updates\\Downloads"
    - "C:\\temp\\update-installer"

- name: patch - check update installer version
  win_shell: >
              {{ ibm_infosvr_install_location.win }}\Updates\bin\installUpdates.exe -version
  register: __ibm_infosvr_update_installer_version
  changed_when: False

- name: patch - transfer update installer
  win_copy:
    src: "{{ ibm_infosvr_media_dir }}/{{ ibm_infosvr_updater.win }}"
    dest: "C:\\temp\\{{ ibm_infosvr_updater.win }}"
  when: __ibm_infosvr_update_installer_version.stdout.find(ibm_infosvr_updater.version) == -1

- name: patch - extract update installer
  win_unzip:
    src: "C:\\temp\\{{ ibm_infosvr_updater.win }}"
    dest: "C:\\temp\\update-installer"
    rm: False
  when: __ibm_infosvr_update_installer_version.stdout.find(ibm_infosvr_updater.version) == -1

- name: patch - update the update installer
  # Bit of ridiculousness because there is a useless 'pause' statement at the end of the update installer which blocks completion otherwise
  raw: "0 | cmd /c C:\\temp\\update-installer\\updateImage.bat -i {{ ibm_infosvr_install_location.win }}\\_uninstall"
  when: __ibm_infosvr_update_installer_version.stdout.find(ibm_infosvr_updater.version) == -1

##########
# EXTRACT UPDATE MEDIA
# This is a separate step from unarchive to allow files to be transferred independently to save time / bandwidth
- name: patch - transfer updates
  win_copy:
    src: "{{ ibm_infosvr_media_dir }}/{{ item.srcFile }}"
    dest: "{{ ibm_infosvr_install_location.win }}\\Updates\\Downloads\\{{ item.srcFile }}"
    creates: "{{ ibm_infosvr_install_location.win }}\\Updates\\Downloads\\{{ item.srcFile }}"
  with_items: "{{ ibm_infosvr_patches_list }}"
  when: ibm_infosvr_version_xml.find(item.versionInfo) == -1

- name: patch - extract updates
  win_unzip:
    src: "{{ ibm_infosvr_install_location.win }}\\Updates\\Downloads\\{{ item.srcFile }}"
    dest: "{{ ibm_infosvr_install_location.win }}\\Updates\\Downloads"
    creates: "{{ ibm_infosvr_install_location.win }}\\Updates\\Downloads\\{{ item.pkgFile }}"
    rm: False
  with_items: "{{ ibm_infosvr_patches_list }}"
  when: ibm_infosvr_version_xml.find(item.versionInfo) == -1

##########
# INSTALL UPDATES
- name: patch - install updates
  win_shell: >
              {{ ibm_infosvr_install_location.win }}\Updates\bin\installUpdates.exe
              -installLocation {{ ibm_infosvr_install_location.win }}
              -patchPackage {{ ibm_infosvr_install_location.win }}\Updates\Downloads\{{ item.pkgFile }}
              -user {{ ibm_infosvr_user_isadmin }}
              -password {{ ibm_infosvr_upwd_isadmin }}
              -console
              -wasadmin {{ ibm_infosvr_user_was }}
              -waspassword {{ ibm_infosvr_upwd_was }}
              -acceptlicense
              -dbadmin {{ ibm_infosvr_user_db2_instance }}
              -dbpassword {{ ibm_infosvr_upwd_db2_instance }}
              {% if ibm_infosvr_force.patch is defined and ibm_infosvr_force.patch %}-force{% endif %}
  with_items: "{{ ibm_infosvr_patches_list }}"
  when: ibm_infosvr_version_xml.find(item.versionInfo) == -1

- name: patch - clean up installation files
  win_file: path={{ item.file }} state={{ item.state }}
  with_items:
    - { file: "{{ ibm_infosvr_install_location.win }}\\Updates\\Backup.*", state: 'absent' }
    - { file: "{{ ibm_infosvr_install_location.win }}\\Updates\\Downloads\\*.zip", state: 'absent' }
  ignore_errors: yes
