---
###
# Copyright 2018 IBM Corp. All Rights Reserved.
# 
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
# 
#      http://www.apache.org/licenses/LICENSE-2.0
# 
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
###

- import_tasks: refresh_install_details.yml

##########
# SETUP
- name: repo - install repository-specific packages
  yum: state=latest name={{ item }}
  with_items:
    - libaio

- name: repo - create required groups
  group: name={{ item }}
  with_items:
    - "{{ ibm_infosvr_group_db2_instance }}"
    - "{{ ibm_infosvr_group_db2_fenced }}"
    - "{{ ibm_infosvr_user_xmeta }}"
    - "{{ ibm_infosvr_user_odb }}"
    - "{{ ibm_infosvr_user_staging }}"
    - "{{ ibm_infosvr_user_ia }}"
    - "{{ ibm_infosvr_user_srd }}"

- name: repo - create required users
  user: name={{ item.user }} group={{ item.group }} password={{ item.password }} shell=/bin/bash
  with_items:
    # NOTE: the passwords must be sha512-hashed to work properly with Ansible's user setup (second parameter is a salt to avoid changes)
    - { group: "{{ ibm_infosvr_group_db2_instance }}", user: "{{ ibm_infosvr_user_db2_instance }}", password: "{{ ibm_infosvr_upwd_db2_instance |password_hash('sha512', ibm_infosvr_salt) }}" }
    - { group: "{{ ibm_infosvr_group_db2_fenced }}", user: "{{ ibm_infosvr_user_db2_fenced }}", password: "{{ ibm_infosvr_upwd_db2_fenced |password_hash('sha512', ibm_infosvr_salt) }}" }
    - { group: "{{ ibm_infosvr_user_xmeta }}", user: "{{ ibm_infosvr_user_xmeta }}", password: "{{ ibm_infosvr_upwd_xmeta |password_hash('sha512', ibm_infosvr_salt) }}" }
    - { group: "{{ ibm_infosvr_user_odb }}", user: "{{ ibm_infosvr_user_odb }}", password: "{{ ibm_infosvr_upwd_odb |password_hash('sha512', ibm_infosvr_salt) }}" }
    - { group: "{{ ibm_infosvr_user_staging }}", user: "{{ ibm_infosvr_user_staging }}", password: "{{ ibm_infosvr_upwd_staging |password_hash('sha512', ibm_infosvr_salt) }}" }
    - { group: "{{ ibm_infosvr_user_ia }}", user: "{{ ibm_infosvr_user_ia }}", password: "{{ ibm_infosvr_upwd_ia |password_hash('sha512', ibm_infosvr_salt) }}" }
    - { group: "{{ ibm_infosvr_user_srd }}", user: "{{ ibm_infosvr_user_srd }}", password: "{{ ibm_infosvr_upwd_srd |password_hash('sha512', ibm_infosvr_salt) }}" }

- name: repo - apply response file template
  template: src=repo-v{{ __ibm_infosvr_version|replace(".", "") }}.j2 dest={{ ibm_infosvr_tmp.linux }}/is-suite/repo.rsp owner=root group=root mode=0644
  when: (ibm_infosvr_version_xml.find('repository="true"') == -1)

- name: repo - parse repository-specific variables
  include_vars: file=repo.yml

- import_tasks: kernel-and-firewall.yml

##########
# BASE INSTALLATION
- name: repo - install repository tier silently
  # Force the install to ensure it bypasses a check that at least 4GB memory is available
  shell: >
          {{ ibm_infosvr_tmp.linux }}/is-suite/setup
          -rsp {{ ibm_infosvr_tmp.linux }}/is-suite/repo.rsp
          -force
  when: (ibm_infosvr_version_xml.find('repository="true"') == -1)

# Next two tasks for RHEL 7 and v11.5 only (http://www-01.ibm.com/support/docview.wss?uid=swg21964393)
- name: repo - configure systemd restartability
  template:
    src: db2fmcd.service.j2
    dest: /etc/systemd/system/db2fmcd.service
    owner: root
    group: root
    mode: 0644
  when: >
        (ansible_distribution == "RedHat" or ansible_distribution == "CentOS")
        and (ansible_distribution_major_version == "7")
        and (__ibm_infosvr_version == "11.5")

- name: repo - register DB2 in systemd
  systemd: name=db2fmcd enabled=yes state=started daemon_reload=yes
  when: >
        (ansible_distribution == "RedHat" or ansible_distribution == "CentOS")
        and (ansible_distribution_major_version == "7")
        and (__ibm_infosvr_version == "11.5")
