---
###
# Copyright 2018 IBM Corp. All Rights Reserved.
# 
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
# 
#      http://www.apache.org/licenses/LICENSE-2.0
# 
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
###

- name: update - update all existing packages
  yum:
    state: latest
    name: '*'
    exclude: docker*,kubelet*,kubectl*,kubeadm*
  become_user: root
  become: yes
  when: not ('ibm-information-server-clients' in group_names)

- name: update - close any active user sessions
  shell: >
          ./SessionAdmin.sh
          -url https://{{ ibm_infosvr_hosts.domain }}:{{ ibm_infosvr_ports.console }}
          -user {{ ibm_infosvr_user_isadmin }}
          -password {{ ibm_infosvr_upwd_isadmin }}
          -kill-user-sessions
  args:
    chdir: "{{ ibm_infosvr_install_location.linux }}/ASBServer/bin"
  become_user: root
  become: yes
  when: ('ibm-information-server-domain' in group_names)
  changed_when: False

- name: update - put server into maintenance mode
  shell: >
          ./SessionAdmin.sh
          -url https://{{ ibm_infosvr_hosts.domain }}:{{ ibm_infosvr_ports.console }}
          -user {{ ibm_infosvr_user_isadmin }}
          -password {{ ibm_infosvr_upwd_isadmin }}
          -set-maint-mode ON
  args:
    chdir: "{{ ibm_infosvr_install_location.linux }}/ASBServer/bin"
  become_user: root
  become: yes
  when: ('ibm-information-server-domain' in group_names)
  changed_when: False

- name: update - parse domain-specific patches
  include_vars: file=patches/domain-v{{ __ibm_infosvr_version|replace(".", "") }}.yml

- import_tasks: patch_linux.yml
  become_user: root
  become: yes
  when: ('ibm-information-server-domain' in group_names)

- name: update - parse engine-specific patches
  include_vars: file=patches/engine-v{{ __ibm_infosvr_version|replace(".", "") }}.yml

- import_tasks: patch_linux.yml
  become_user: root
  become: yes
  when: ('ibm-information-server-engine' in group_names)

- name: update - remove server from maintenance mode
  shell: >
          ./SessionAdmin.sh
          -url https://{{ ibm_infosvr_hosts.domain }}:{{ ibm_infosvr_ports.console }}
          -user {{ ibm_infosvr_user_isadmin }}
          -password {{ ibm_infosvr_upwd_isadmin }}
          -set-maint-mode OFF
  args:
    chdir: "{{ ibm_infosvr_install_location.linux }}/ASBServer/bin"
  become_user: root
  become: yes
  when: ('ibm-information-server-domain' in group_names)
  changed_when: False

- name: update - parse client-specific patches
  include_vars: file=patches/client-v{{ __ibm_infosvr_version|replace(".", "") }}.yml

- import_tasks: patch_win.yml
  when: ('ibm-information-server-clients' in group_names)
