---
###
# Copyright 2018 IBM Corp. All Rights Reserved.
# 
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
# 
#      http://www.apache.org/licenses/LICENSE-2.0
# 
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
###

- name: update-jdk - parse engine-specific patches
  include_vars: file=patches/engine-v{{ __ibm_infosvr_version|replace(".", "") }}.yml

- name: update-jdk - parse domain-specific patches
  include_vars: file=patches/domain-v{{ __ibm_infosvr_version|replace(".", "") }}.yml

- name: update-jdk - check existing InfoSvr JDK version
  shell: "{{ ibm_infosvr_install_location.linux }}/jdk/bin/java -version"
  register: __ibm_infosvr_existing_jdk_version
  changed_when: False

- name: update-jdk - check existing WebSphere JDK version
  shell: >
          {{ ibm_infosvr_install_location.was }}/java{{ (__ibm_infosvr_version == "11.5") | ternary('','/8.0') }}/bin/java -version
  register: __ibm_infosvr_websphere_existing_jdk_version
  changed_when: False
  when: ('ibm-information-server-domain' in group_names)

- name: update-jdk - check existing WebSphere JDK7 version (v11.5)
  shell: "{{ ibm_infosvr_install_location.was }}/java_1.7_64/bin/java -version"
  register: __ibm_infosvr_websphere_existing_jdk7_version
  changed_when: False
  when: ('ibm-information-server-domain' in group_names) and __ibm_infosvr_version == "11.5"

- name: stopping Information Server
  raw: echo 0
  when: >
        (ibm_infosvr_jdk_update is defined and __ibm_infosvr_existing_jdk_version.stderr.find(ibm_infosvr_jdk_update[0].versionInfo) == -1)
        or (ibm_infosvr_websphere_jdk_update is defined and __ibm_infosvr_websphere_existing_jdk_version.stderr.find(ibm_infosvr_websphere_jdk_update[0].versionInfo) == -1)
        or (ibm_infosvr_websphere_jdk7_update is defined and __ibm_infosvr_websphere_existing_jdk7_version.stderr.find(ibm_infosvr_websphere_jdk7_update[0].versionInfo) == -1)
  notify:
    - "stop IBM InfoSphere Information Server"

- meta: flush_handlers

- import_tasks: patch_jdk_infosvr.yml
  become_user: root
  become: yes
  when: >
        ('ibm-information-server-engine' in group_names)
        and (ibm_infosvr_jdk_update is defined)
        and __ibm_infosvr_existing_jdk_version.stderr.find(ibm_infosvr_jdk_update[0].versionInfo) == -1

- import_tasks: patch_jdk_was.yml
  become_user: root
  become: yes
  when: >
        ('ibm-information-server-domain' in group_names)
        and not (__ibm_infosvr_features.wlp)
        and (ibm_infosvr_websphere_jdk_update is defined)
        and __ibm_infosvr_websphere_existing_jdk_version.stderr.find(ibm_infosvr_websphere_jdk_update[0].versionInfo) == -1

- import_tasks: patch_jdk7_was.yml
  become_user: root
  become: yes
  when: >
        ('ibm-information-server-domain' in group_names)
        and not (__ibm_infosvr_features.wlp)
        and (ibm_infosvr_websphere_jdk7_update is defined)
        and __ibm_infosvr_websphere_existing_jdk7_version.stderr.find(ibm_infosvr_websphere_jdk7_update[0].versionInfo) == -1

- name: starting Information Server
  raw: echo 0
  when: >
        (ibm_infosvr_jdk_update is defined and __ibm_infosvr_existing_jdk_version.stderr.find(ibm_infosvr_jdk_update[0].versionInfo) == -1)
        or (ibm_infosvr_websphere_jdk_update is defined and __ibm_infosvr_websphere_existing_jdk_version.stderr.find(ibm_infosvr_websphere_jdk_update[0].versionInfo) == -1)
        or (ibm_infosvr_websphere_jdk7_update is defined and __ibm_infosvr_websphere_existing_jdk7_version.stderr.find(ibm_infosvr_websphere_jdk7_update[0].versionInfo) == -1)
  notify:
    - "start IBM InfoSphere Information Server"

- meta: flush_handlers
