---
###
# Copyright 2018 IBM Corp. All Rights Reserved.
# 
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
# 
#      http://www.apache.org/licenses/LICENSE-2.0
# 
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
###

- name: stop IBM InfoSphere Information Server Data Flow Designer
  shell: "./stopCognitiveDesignerServer.sh"
  args:
    executable: /bin/bash
    chdir: "{{ ibm_infosvr_install_location.linux }}/ASBNode/CognitiveDesignerEngine"
  become_user: root
  become: yes
  ignore_errors: yes
  changed_when: False
  when: ('ibm-information-server-engine' in group_names)
  listen:
    - "restart IBM InfoSphere Information Server"
    - "stop IBM InfoSphere Information Server"

- name: stop IBM InfoSphere Information Server DataStage services
  shell: "cd `cat /.dshome` && . dsenv && ./bin/uv -admin -stop"
  args:
    executable: /bin/bash
  become_user: "{{ ibm_infosvr_user_dsadmin }}"
  become: yes
  ignore_errors: yes
  changed_when: False
  when: ('ibm-information-server-engine' in group_names)
  listen:
    - "restart IBM InfoSphere Information Server"
    - "stop IBM InfoSphere Information Server"

- name: stop IBM InfoSphere Information Server NodeAgents
  shell: "./NodeAgents.sh stop"
  args:
    executable: /bin/bash
    chdir: "{{ ibm_infosvr_install_location.linux }}/ASBNode/bin"
  become_user: root
  become: yes
  ignore_errors: yes
  changed_when: False
  when: ('ibm-information-server-engine' in group_names)
  listen:
    - "restart IBM InfoSphere Information Server"
    - "stop IBM InfoSphere Information Server"

- name: stop IBM InfoSphere Information Server DSAppWatcher
  shell: "./DSAppWatcher.sh -stop"
  args:
    executable: /bin/bash
    chdir: "{{ ibm_infosvr_install_location.linux }}/Server/DSODB/bin"
  become_user: "{{ ibm_infosvr_user_dsadmin }}"
  become: yes
  ignore_errors: yes
  changed_when: False
  when: ('ibm-information-server-engine' in group_names) and __ibm_infosvr_features.opsdb
  listen:
    - "restart IBM InfoSphere Information Server"
    - "stop IBM InfoSphere Information Server"

- name: stop IBM InfoSphere Information Server application server
  shell: "./MetadataServer.sh stop"
  args:
    executable: /bin/bash
    chdir: "{{ ibm_infosvr_install_location.linux }}/ASBServer/bin"
  become_user: root
  become: yes
  ignore_errors: yes
  changed_when: False
  when: ('ibm-information-server-domain' in group_names)
  listen:
    - "restart IBM InfoSphere Information Server"
    - "stop IBM InfoSphere Information Server"

- name: stop IBM InfoSphere Information Server Kafka
  systemd: state=stopped name=InfoSrvKafka
  become_user: root
  become: yes
  ignore_errors: yes
  changed_when: False
  when: ('ibm-information-server-domain' in group_names)
  listen:
    - "restart IBM InfoSphere Information Server"
    - "stop IBM InfoSphere Information Server"
    - "re-generate config for open source utilities"

- name: stop IBM InfoSphere Information Server Solr
  systemd: state=stopped name=InfoSrvSolrCloud
  become_user: root
  become: yes
  ignore_errors: yes
  changed_when: False
  when: ('ibm-information-server-domain' in group_names)
  listen:
    - "restart IBM InfoSphere Information Server"
    - "stop IBM InfoSphere Information Server"
    - "re-generate config for open source utilities"

- name: stop IBM InfoSphere Information Server Zookeeper
  systemd: state=stopped name=InfoSrvZookeeper
  become_user: root
  become: yes
  ignore_errors: yes
  changed_when: False
  when: ('ibm-information-server-domain' in group_names)
  listen:
    - "restart IBM InfoSphere Information Server"
    - "stop IBM InfoSphere Information Server"
    - "re-generate config for open source utilities"

- name: stop IBM InfoSphere Information Server ODFEngine (v11.7)
  systemd: state=stopped name=ODFEngine
  become_user: root
  become: yes
  ignore_errors: yes
  changed_when: False
  when: ('ibm-information-server-domain' in group_names) and __ibm_infosvr_version == "11.7"
  listen:
    - "restart IBM InfoSphere Information Server"
    - "stop IBM InfoSphere Information Server"
    - "re-generate config for open source utilities"

- name: re-generate open source utilities configuration
  shell: "{{ item }}"
  with_items:
    - "{{ ibm_infosvr_install_location.linux }}/shared-open-source/zookeeper/update-config.sh"
    - "{{ ibm_infosvr_install_location.linux }}/shared-open-source/solr/update-config.sh"
    - "{{ ibm_infosvr_install_location.linux }}/shared-open-source/kafka/update-config.sh"
  become_user: root
  become: yes
  when: ('ibm-information-server-domain' in group_names)
  listen:
    - "re-generate config for open source utilities"

- name: start IBM InfoSphere Information Server Zookeeper
  systemd: state=started name=InfoSrvZookeeper
  become_user: root
  become: yes
  retries: 3
  delay: 5
  register: __ibm_infosvr_os_start_zookeeper_result
  until: __ibm_infosvr_os_start_zookeeper_result.status.Result == "success"
  changed_when: False
  when: ('ibm-information-server-domain' in group_names)
  listen:
    - "restart IBM InfoSphere Information Server"
    - "start IBM InfoSphere Information Server"
    - "re-generate config for open source utilities"

- name: start IBM InfoSphere Information Server Solr
  systemd: state=started name=InfoSrvSolrCloud
  become_user: root
  become: yes
  retries: 3
  delay: 5
  register: __ibm_infosvr_os_start_solr_result
  until: __ibm_infosvr_os_start_solr_result.status.Result == "success"
  changed_when: False
  when: ('ibm-information-server-domain' in group_names)
  listen:
    - "restart IBM InfoSphere Information Server"
    - "start IBM InfoSphere Information Server"
    - "re-generate config for open source utilities"

- name: start IBM InfoSphere Information Server open source utilities
  systemd: state=started name=InfoSrvKafka
  become_user: root
  become: yes
  retries: 3
  delay: 5
  register: __ibm_infosvr_os_start_kafka_result
  until: __ibm_infosvr_os_start_kafka_result.status.Result == "success"
  changed_when: False
  when: ('ibm-information-server-domain' in group_names)
  listen:
    - "restart IBM InfoSphere Information Server"
    - "start IBM InfoSphere Information Server"
    - "re-generate config for open source utilities"

- name: start IBM InfoSphere Information Server ODFEngine (v11.7)
  systemd: state=started name=ODFEngine
  become_user: root
  become: yes
  ignore_errors: yes
  changed_when: False
  when: ('ibm-information-server-domain' in group_names) and __ibm_infosvr_version == "11.7"
  listen:
    - "restart IBM InfoSphere Information Server"
    - "start IBM InfoSphere Information Server"
    - "re-generate config for open source utilities"

- name: start IBM InfoSphere Information Server application server
  shell: "./MetadataServer.sh run"
  args:
    executable: /bin/bash
    chdir: "{{ ibm_infosvr_install_location.linux }}/ASBServer/bin"
  become_user: root
  become: yes
  changed_when: False
  when: ('ibm-information-server-domain' in group_names)
  listen:
    - "restart IBM InfoSphere Information Server"
    - "start IBM InfoSphere Information Server"

- name: start IBM InfoSphere Information Server NodeAgents
  shell: "./NodeAgents.sh start"
  args:
    executable: /bin/bash
    chdir: "{{ ibm_infosvr_install_location.linux }}/ASBNode/bin"
  become_user: root
  become: yes
  changed_when: False
  when: ('ibm-information-server-engine' in group_names)
  listen:
    - "restart IBM InfoSphere Information Server"
    - "start IBM InfoSphere Information Server"

- name: start IBM InfoSphere Information Server DataStage services
  shell: "cd `cat /.dshome` && . dsenv && ./bin/uv -admin -start"
  args:
    executable: /bin/bash
  become_user: "{{ ibm_infosvr_user_dsadmin }}"
  become: yes
  changed_when: False
  when: ('ibm-information-server-engine' in group_names)
  listen:
    - "restart IBM InfoSphere Information Server"
    - "start IBM InfoSphere Information Server"

- name: start IBM InfoSphere Information Server DSAppWatcher
  shell: "./DSAppWatcher.sh -start"
  args:
    executable: /bin/bash
    chdir: "{{ ibm_infosvr_install_location.linux }}/Server/DSODB/bin"
  become_user: "{{ ibm_infosvr_user_dsadmin }}"
  become: yes
  changed_when: False
  when: ('ibm-information-server-engine' in group_names) and __ibm_infosvr_features.opsdb
  listen:
    - "restart IBM InfoSphere Information Server"
    - "start IBM InfoSphere Information Server"

- name: start IBM InfoSphere Information Server Data Flow Designer
  shell: "./startCognitiveDesignerServer.sh"
  args:
    executable: /bin/bash
    chdir: "{{ ibm_infosvr_install_location.linux }}/ASBNode/CognitiveDesignerEngine"
  become_user: root
  become: yes
  changed_when: False
  when: ('ibm-information-server-engine' in group_names) and __ibm_infosvr_version == "11.7"
  listen:
    - "restart IBM InfoSphere Information Server"
    - "start IBM InfoSphere Information Server"
